const fs = require('node:fs');
const path = require('node:path');
const assert = require('node:assert/strict');
const { JSDOM } = require('jsdom');
const base = process.env.NEUROCARE_WEB_PATH || path.resolve(__dirname, '../../src/NeuroCare.Web');
const view = fs.readFileSync(path.join(base, 'Views/Documents/Upload.cshtml'), 'utf8');
assert.ok(view.includes('data-max-bytes="@Storage.MaxFileBytes"'));
assert.ok(view.includes('~/js/upload-check.js'));
const dom = new JSDOM('<form><input id="file" type="file" data-max-bytes="1024" data-error-target="file-error"><div id="file-error" class="d-none"></div><button type="submit">Enviar</button></form>', { runScripts: 'outside-only' });
dom.window.eval(fs.readFileSync(path.join(base, 'wwwroot/js/upload-check.js'), 'utf8'));
const input = dom.window.document.querySelector('input');
const message = dom.window.document.querySelector('#file-error');
Object.defineProperty(input, 'files', { configurable: true, value: [{ size: 1025 }] });
input.dispatchEvent(new dom.window.Event('change'));
assert.equal(message.classList.contains('d-none'), false);
assert.ok(message.textContent.includes('Reduza o arquivo'));
Object.defineProperty(input, 'files', { configurable: true, value: [{ size: 1024 }] });
input.dispatchEvent(new dom.window.Event('change'));
assert.equal(message.classList.contains('d-none'), true);
dom.window.document.querySelector('form').dispatchEvent(new dom.window.Event('submit', { cancelable: true }));
assert.equal(dom.window.document.querySelector('button').disabled, true);
dom.window.close();
console.log('Upload: limite excedido, limite exato e estado de envio verificados.');
